#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("scripting.Droid.Resource", IsApplication=true)]

namespace scripting.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int abdomen = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int actor = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int airplane = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int airport = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ancient = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int angry = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int apartment = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int apple = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ar_bg = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int br_bg = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ch_bg = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int cn_bg = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int de_bg = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int dog = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int es_bg = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int fr_bg = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int gb_bg = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int it_bg = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int jp_bg = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int learn = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int learn2 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int monkey = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int mx_bg = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ru_bg = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int settings = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int settings2 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int sound_off = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int sound_on = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int test = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int test2 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int us_bg = 2130837534;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070002
			public const int imageView1 = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int tabView1 = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int textView1 = 2131165185;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int fragment = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Main = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int Your_TabText_Style = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
